### PR TITLE
Add SZ

### PR DESCRIPTION
**Pull request by willirath**

### CODE REVIEW

**Comment by willirath** [comment]
38aa1c7 should install a working™️ `pysz`. One thing left to do: It does not find the `libSZ.so` without explicitly setting the `LD_LIBRARY_PATH`.

**Comment by willirath** [comment]
Dirty library loading trick (use in a Jupyter notebook):
```python
from ctypes import cdll
lib1 = cdll.LoadLibrary('/home/jovyan/pysz/lib/libSZ.so')
lib2 = cdll.LoadLibrary('/home/jovyan/pysz/lib/libzstd.so')

import pysz
```

**Comment by ucyo** [comment]
Are the variables `lib1` and `lib2` used? Or ignored?

**Comment by willirath** [comment]
They are ignored.

**Comment by ucyo** [comment]
Just tested the new setup. I tested it and it seems to be working. But I discovered #13

**Comment by ucyo** [comment]
If we can be use that #13 is not a problem at our end (do not see a reason why not), we should merge.

**Pull request merged**
